### ISSUE TITLE
TAZ: Heated bed not heating

### ISSUE THREAD

**Issue by jubeormk1** [CCHS-Melbourne/3D-Printers#6]
Doing a basic test in the printer looks like the bed heater is not heating. I did some test after disconnecting the modular Anderson connectors:
- I open the connector for the heated bed checked the voltage going to the heating bed and looks fine
- The measured resistance of the heating bed is 1.5 Ohms

Maybe continuity issues on the cable?

**Comment by brainstorm** [comment]
Did some thorough testing and concluded that the bed heating element was the one at fault, but it turns out I was wrong? Can you double check these pictures, @jubeormk1 ?

Troubleshooting steps:

1) Disconnect the heated bed connector and measure 22-23V on the connector end that comes from the 3D printer.
2) Connect the bed to a lab power supply at 24V (as shown in the label) and see that it doesn't get hot at all with the temperature probe.
3) Remove/desolder the connector from the bed (to rule out a short in there) and connect the lab power supply to the resistor leads on the bed (bypassing the connector altogether). Same result as 2.
4) Connect the new bed resistive element to the lab power supply, see that it increases temperature after a few seconds of drawing ~3A@24V.
5) Rip off the old bed and glue the new one.
6) Connect it back to the printer and fail :_(

![IMG_1971](https://user-images.githubusercontent.com/175587/151647731-73de0acc-5b6a-430a-bfef-71a501ba84b8.JPG)
![IMG_1972](https://user-images.githubusercontent.com/175587/151647735-95ca52f5-e187-4b48-b926-b205a629d61c.JPG)
![IMG_1973](https://user-images.githubusercontent.com/175587/151647740-08e3b243-0540-4c8d-92bf-553016218450.JPG)
![IMG_1974](https://user-images.githubusercontent.com/175587/151647742-9166b24c-36f6-4ace-981a-0f43aa47d26e.JPG)
![IMG_1975](https://user-images.githubusercontent.com/175587/151647746-aeb62ffb-e4a1-498d-9f4e-9d44622f7e75.JPG)
![IMG_1976](https://user-images.githubusercontent.com/175587/151647747-230b8a6c-c1c7-4ed5-a629-5770eb1a6317.JPG)
![IMG_1977](https://user-images.githubusercontent.com/175587/151647748-94c23dd3-2065-4131-9b12-a83e831ab7fa.JPG)
![IMG_1978](https://user-images.githubusercontent.com/175587/151647751-b12c598f-5481-4c01-92bf-312670b7ebdd.JPG)
![IMG_1979](https://user-images.githubusercontent.com/175587/151647754-c50a8146-02ba-4cac-8ca6-9ddc0789b070.JPG)
![IMG_1980](https://user-images.githubusercontent.com/175587/151647755-d0788840-f0b5-4803-8987-f4f7ebae0c9d.JPG)
![IMG_1981](https://user-images.githubusercontent.com/175587/151647760-8fa09f46-d9d9-4656-a52f-9ebc78f4983a.JPG)

**Comment by brainstorm** [comment]
Will check the automotive fuse they mention here...: https://forum.lulzbot.com/t/taz-bed-not-heating-up-help-with-troubleshooting/5060/6

**Comment by brainstorm** [comment]
Nope, the fuse is fine :/


![IMG_1983](https://user-images.githubusercontent.com/175587/151650108-04fca1da-cc16-4172-987e-de6d75be5465.JPG)

![IMG_1982](https://user-images.githubusercontent.com/175587/151650104-e7e882d7-1aef-4dc6-91cc-80781f657593.JPG)

**Comment by brainstorm** [comment]
Fixed! It was the bed connector that goes from the "Rambo" board (mainboard of the TAZ) to the bed connector... the internal leads were bent and were not doing proper contact, I managed to print a calibrator cat today, thanks everybody for the suggestions over Discord and elsewhere :)

**Comment by brainstorm** [comment]
The bed connector is unreliable, needs to be replaced.

**Comment by brainstorm** [comment]
Found the real culprit and fixed it today for good... the convenience of connectors is overrated.


![IMG_2031](https://user-images.githubusercontent.com/175587/153873338-cdfdf8d1-a4da-4ac3-bd98-b97b3280b0e2.JPG)
![IMG_2030](https://user-images.githubusercontent.com/175587/153873371-ddb8625d-ba25-490c-b928-04fb4479ce79.JPG)
![IMG_2032](https://user-images.githubusercontent.com/175587/153873300-2e21282d-57fa-493a-83b6-887bfbe48919.JPG)
